In [1]:
import os
import io
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrowfs_adlgen2 as pa_adl
import numpy as np
import librosa
import datetime as dt

from dotenv import load_dotenv
from pathlib import Path

from azure.identity import DefaultAzureCredential, ClientSecretCredential
from azure.storage.filedatalake import DataLakeServiceClient
from azure.keyvault.secrets import SecretClient
from azure.core.exceptions import ResourceNotFoundError

from concurrent.futures import ThreadPoolExecutor

In [2]:
# local
DATA_DIR = "../../include/data"

In [7]:
# local
BRONZE_FOLDER_NAME = "bronze"
BRONZE_DATA_DIR = os.path.join("{DATA_DIR}", "{FOLDER_NAME}").replace("\\", "/")
BRONZE_DATA_DIR

'{DATA_DIR}/{FOLDER_NAME}'

In [4]:
# Retrieve credentials from environment variables
# this is strictly used only in development
# load env variables
env_dir = Path('../../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

True

In [5]:
storage_account_name = os.environ.get("STORAGE_ACCOUNT_NAME")
credential = os.environ.get("STORAGE_ACCOUNT_KEY")
conn_str = os.environ.get("STORAGE_ACCOUNT_CONN_STR")

In [9]:
# cloud
URL = "abfss://{FOLDER_NAME}@sgppipelinesa.dfs.core.windows.net"
BRONZE_FOLDER_NAME = "sgppipelinesa-bronze"
BRONZE_DATA_DIR = os.path.join(URL.format(FOLDER_NAME=BRONZE_FOLDER_NAME)).replace("\\", "/")
BRONZE_DATA_DIR

'abfss://sgppipelinesa-bronze@sgppipelinesa.dfs.core.windows.net'

In [10]:
# cloud
# create client with generated sas token
datalake_service_client = DataLakeServiceClient(
    account_url=f"https://{storage_account_name}.dfs.core.windows.net", 
    credential=credential
)

In [11]:
# retrieves file system client/container client 
# to retrieve datalake client
bronze_container_client = datalake_service_client.get_file_system_client(f"{storage_account_name}-bronze")

# https://sgppipelinesa.dfs.core.windows.net/sgppipelinesa-bronze
bronze_container_client_url = bronze_container_client.url

# https://sgppipelinesa.blob.core.windows.net/sgppipelinesa-bronze/1028-20100710-hne/wav/ar-01.wav
path_to_wavs = [
    path.name 
    for path in bronze_container_client.get_paths() if ".wav" in path.name or ".flac" in path.name
]
path_to_wavs

['1028-20100710-hne/wav/ar-01.wav',
 '1028-20100710-hne/wav/ar-02.wav',
 '1028-20100710-hne/wav/ar-03.wav',
 '1028-20100710-hne/wav/ar-04.wav',
 '1028-20100710-hne/wav/ar-05.wav',
 '1028-20100710-hne/wav/ar-06.wav',
 '1028-20100710-hne/wav/ar-07.wav',
 '1028-20100710-hne/wav/rp-29.wav',
 '1028-20100710-hne/wav/rp-30.wav',
 '1028-20100710-hne/wav/rp-31.wav',
 '1337ad-20170321-ajg/wav/en-0532.wav',
 '1337ad-20170321-ajg/wav/en-0533.wav',
 '1337ad-20170321-ajg/wav/en-0534.wav',
 '1337ad-20170321-ajg/wav/en-0535.wav',
 '1337ad-20170321-ajg/wav/en-0536.wav',
 '1337ad-20170321-ajg/wav/en-0537.wav',
 '1337ad-20170321-ajg/wav/en-0538.wav',
 '1337ad-20170321-ajg/wav/en-0539.wav',
 '1337ad-20170321-ajg/wav/en-0540.wav',
 '1337ad-20170321-ajg/wav/en-0541.wav',
 '1337ad-20170321-tkg/wav/en-0726.wav',
 '1337ad-20170321-tkg/wav/en-0727.wav',
 '1337ad-20170321-tkg/wav/en-0728.wav',
 '1337ad-20170321-tkg/wav/en-0729.wav',
 '1337ad-20170321-tkg/wav/en-0730.wav',
 '1337ad-20170321-tkg/wav/en-0731.wav',


In [34]:
sample_path_to_wavs = [path.name for path in bronze_container_client.get_paths(path='1028-20100710-hne/wav')]
sample_path_to_wavs

['1028-20100710-hne/wav/ar-01.wav',
 '1028-20100710-hne/wav/ar-02.wav',
 '1028-20100710-hne/wav/ar-03.wav',
 '1028-20100710-hne/wav/ar-04.wav',
 '1028-20100710-hne/wav/ar-05.wav',
 '1028-20100710-hne/wav/ar-06.wav',
 '1028-20100710-hne/wav/ar-07.wav',
 '1028-20100710-hne/wav/rp-29.wav',
 '1028-20100710-hne/wav/rp-30.wav',
 '1028-20100710-hne/wav/rp-31.wav']

In [44]:
path_to_wavs[0].split("/")[-3]

'1028-20100710-hne'

# Once all paths from bronze are extracted get only the ones that don't already exist in the paths silver/stage-01

In [12]:
# # cloud
# # URL = "abfss://{FOLDER_NAME}@sgppipelinesa.dfs.core.windows.net"
# URL = "{FOLDER_NAME}"
# SILVER_FOLDER_NAME = "sgppipelinesa-silver"
# SUB_FOLDER_NAME = "stage-01"
# SILVER_DATA_DIR = os.path.join(URL, "{SUB_FOLDER_NAME}").replace("\\", "/")
# SILVER_DATA_DIR

# local
SILVER_FOLDER_NAME = "silver"
SUB_FOLDER_NAME = "stage-01"
SILVER_DATA_DIR = os.path.join("{DATA_DIR}", "{FOLDER_NAME}", "{SUB_FOLDER_NAME}").replace("\\", "/")
SILVER_DATA_DIR

'{DATA_DIR}/{FOLDER_NAME}/{SUB_FOLDER_NAME}'

In [ ]:
# # cloud
# # retrieves file system client/container client 
# # to retrieve datalake client
# silver_container_client = datalake_service_client.get_file_system_client(f"{storage_account_name}-silver")

# # https://sgppipelinesa.dfs.core.windows.net/sgppipelinesa-silver
# silver_container_client_url = silver_container_client.url

# # https://sgppipelinesa.blob.core.windows.net/sgppipelinesa-silver/1028-20100710-hne/wav/ar-01.wav
# subject_folders = [
#     path.name 
#     for path in silver_container_client.get_paths(path="stage-01/")
# ]
# subject_folders

In [13]:
# local
signal_file_paths = [
    str(signal_file_path).replace("\\", "/") for signal_file_path in Path(
        SILVER_DATA_DIR.format(
            DATA_DIR=DATA_DIR,
            FOLDER_NAME=SILVER_FOLDER_NAME,
            SUB_FOLDER_NAME=SUB_FOLDER_NAME
        )
    ).rglob('*')  
    if signal_file_path.is_file() and "labels" not in str(signal_file_path)
]
signal_file_paths

['../../include/data/silver/stage-01/1028-20100710-hne/ar-01.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-02.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-03.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-04.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-05.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-06.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/ar-07.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/rp-29.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/rp-30.parquet',
 '../../include/data/silver/stage-01/1028-20100710-hne/rp-31.parquet',
 '../../include/data/silver/stage-01/1337ad-20170321-ajg/en-0532.parquet',
 '../../include/data/silver/stage-01/1337ad-20170321-ajg/en-0533.parquet',
 '../../include/data/silver/stage-01/1337ad-20170321-ajg/en-0534.parquet',
 '../../include/data/silver/stage-01/1337ad-20170321-ajg/en-0535.

In [15]:
def filter_path_to_wavs(bronze_path_to_wavs, silver_stage_01_path_to_signals):
    """
    we compare this:
    
    ['1337ad-20170321-tkg/wav/en-0729.wav',
    '1337ad-20170321-tkg/wav/en-0730.wav',
    ...
    'Coren-20141121-pxp/wav/b0472.wav',
    'Coren-20141121-pxp/wav/b0473.wav',
    'Coren-20141121-pxp/wav/b0474.wav',
    'Coren-20141121-pxp/wav/b0475.wav',
    'Coren-20141121-pxp/wav/b0476.wav']
    
    to this:
    
    [ '../../include/data/silver/stage-01/1337ad-20170321-tkg/en-0730.parquet',
    ...
    '../../include/data/silver/stage-01/Coren-20141121-pxp/b0472.parquet',
    '../../include/data/silver/stage-01/Coren-20141121-pxp/b0473.parquet',
    '../../include/data/silver/stage-01/Coren-20141121-pxp/b0474.parquet',
    '../../include/data/silver/stage-01/Coren-20141121-pxp/b0475.parquet',
    '../../include/data/silver/stage-01/Coren-20141121-pxp/b0476.parquet']
    
    but we need to normalize both lists to be just the subject folder and its 
    corresponding wav file name without the extension, and conversely subject
    folder in silver/stage-01/ and its corresponding parquet file name 
    without the extension. E.g. 1337ad-20170321-tkg/wav/en-0729.wav becomes
    1337ad-20170321-tkg/en-0729 and 
    ../../include/data/silver/stage-01/1337ad-20170321-tkg/en-0730.parquet 
    becomes 1337ad-20170321-tkg/en-0730
    """
    
    normalized_bronze_path_to_wavs_map = dict(zip(
        bronze_path_to_wavs,
        [
            os.path.join(
                path.split("/")[-3],
                path.split("/")[-1].replace(".wav", "").replace(".flac", "")    
            ).replace("\\", "/")
            for path in bronze_path_to_wavs
        ],
    ))

    normalized_silver_stage_01_path_to_signals = [
        os.path.join(
            path.split("/")[-2],
            path.split("/")[-1].replace(".parquet", "")
        ).replace("\\", "/")
        for path in silver_stage_01_path_to_signals
    ]

    return [
        key for key, normalized_path_to_wav in normalized_bronze_path_to_wavs_map.items()
        if normalized_path_to_wav not in normalized_silver_stage_01_path_to_signals
    ]

In [16]:
# # append test .wav path to see if it gets filtered out 
# # since it won't have a corresponding parquet file in 
# # silver/stage-01
# path_to_wavs.append("test_subject/wav/test.wav")
# path_to_wavs.pop()

In [17]:
path_to_wavs_filt = filter_path_to_wavs(path_to_wavs, signal_file_paths)
path_to_wavs_filt

[]

In [18]:
def ingest_signals(path_to_wavs: list[str], DATA_DIR: str=None):
    """
    ingests signals from .wav files, trims the audio signal to 
    remove silence, and writes the trimmed signal as a parquet 
    file in azure data lake or locally depending on where 
    this function is being run.

    Args:
        path_to_wavs (list[str]): _description_
        DATA_DIR (str, optional): _description_. Defaults to None.
    """
    def helper(path_to_wav):
        
        # # local
        # # # lists out the files containing the .wav files in
        # # # a subjects folder. Note also that using double backslash
        # # # is not accepted by azure and will raise `path does not exist
        # # # or `files can not exist on the root account level` that's
        # # # why we replace it always with forward slashes
        # # wavs_dir = os.path.join(DATA_DIR, "bronze", subject_folder, "wav").replace("\\", "/")
        # # path_to_wavs = os.listdir(wavs_dir)

        # wavs_dir = os.path.join(subject_folder, "wav").replace("\\", "/")
        # path_to_wavs = [
        #     path.name 
        #     for path in bronze_container_client.get_paths(path=wavs_dir)
        # ]
        try:
            # get meta data and replace file extension to be 
            # .parquet for later writing as parquet file
            subject_folder = path_to_wav.split("/")[-3]
            new_wav_file_name = path_to_wav.split("/")[-1].replace(".wav", "").replace(".flac", "")
            
            # create storage for list of signals to all be 
            # concatenated later
            signal_list = []
            
            # create storage list for the ordinal positioning
            # of signals to all be concatenated later
            wav_file_row_num_list = []
            file_name_list = []
            loaded_at_list = []
            
            # cloud
            wav_file_client = bronze_container_client.get_file_client(path_to_wav)

            # Download the file content
            download_result = wav_file_client.download_file()
            downloaded_bytes = download_result.readall()
            audio_buff = io.BytesIO(downloaded_bytes)

            # # local
            # audio_buff = os.path.join(wavs_dir, wav)

            # let librosa read the audio buffer containing t+he content
            # of the binary audio file
            y, sr = librosa.load(audio_buff, sr=16000)

            # audio recordings can have different length
            print(f"shape of audio signals {y.shape}")
            print(f"sampling rate of audio signals after interpolation: {sr}")

            # top_db is set to 20 representing any signal belows
            # 20 decibels will be considered silence
            y_trimmed, _ = librosa.effects.trim(y, top_db=20)
            
            # get how many elements/signals there are in the trimmed
            # version
            # >>> y_trimmed, _ = librosa.effects.trim(np.array([[1, 2, 3, 4, 0, 0, 0]]), top_db=20)
            # >>> y_trimmed.shape
            # (1, 7)
            # ordinal positioning will be 0, 1, 2, 3, 4, 5, 6, 7
            ordinal_positioning = np.arange(y_trimmed.shape[0])
            print(ordinal_positioning)

            # append y to ys 
            signal_list.append(y_trimmed)
            wav_file_row_num_list.append(ordinal_positioning)
            file_name_list.append(np.array(
                [os.path.join(bronze_container_client.url, path_to_wav).replace("\\", "/")] * y_trimmed.shape[0],
            ))
            loaded_at_list.append(np.array(
                [dt.datetime.now()] * y_trimmed.shape[0], 
                dtype='datetime64[us]'
            ))

            # concatenate all audio signals into one final signal as 
            # this is all anyway recorded in the voice of the same gender
            signals = np.concatenate(signal_list, axis=0)
            wav_file_row_num = np.concatenate(wav_file_row_num_list, axis=0)
            file_name = np.concatenate(file_name_list, axis=0)
            loaded_at = np.concatenate(loaded_at_list, axis=0)

            # create pyarrow table so we can write this table as
            # parquet file format later
            table = pa.table({
                "signals": pa.array(signals), 
                "subject_id": pa.array([subject_folder] * signals.shape[0], type=pa.string()),
                "wav_file_row_number": pa.array(wav_file_row_num),
                "file_name": pa.array(file_name), 
                "loaded_at": pa.array(loaded_at)
            })

            # # cloud
            # # write the pyarrow table to azure data lake using
            # # pyarrow azure file system using the credential we
            # # retrieved which uses the function apps system assigned 
            # # managed identity
            # SILVER_FOLDER_NAME = f"{storage_account_name}-silver"
            # SUB_FOLDER_NAME = "stage-01"
            # FILE_NAME = f"{subject_folder}_signals.parquet"

            # SILVER_DATA_PATH = os.path.join(SILVER_FOLDER_NAME, SUB_FOLDER_NAME, FILE_NAME).replace("\\", "/")
            # handler = pa_adl.AccountHandler.from_account_name(storage_account_name, credential=credential)
            # fs = pa.fs.PyFileSystem(handler)
            # pq.write_table(table, SILVER_DATA_PATH, filesystem=fs)

            # local
            SILVER_FOLDER_NAME = f"silver"
            SUB_FOLDER_NAME = f"stage-01"
            FILE_NAME = f"{new_wav_file_name}.parquet"
            
            # make directory where the numpyfied signals
            # will live
            SILVER_DATA_DIR = os.path.join(DATA_DIR, SILVER_FOLDER_NAME, SUB_FOLDER_NAME, subject_folder)
            os.makedirs(SILVER_DATA_DIR, exist_ok=True)
            
            # 
            SILVER_DATA_PATH = os.path.join(DATA_DIR, SILVER_FOLDER_NAME, SUB_FOLDER_NAME, subject_folder, FILE_NAME).replace("\\", "/")
            pq.write_table(table, SILVER_DATA_PATH)
        
        except (ResourceNotFoundError, FileNotFoundError):
            print(f"file not found for subject {path_to_wav}, skipping...")
            
                
        return
            
    # concurrently load .wav files and trim  each .wav files
    # audio signal and combine into one signal for each subject 
    with ThreadPoolExecutor(max_workers=2) as exe:
        print("running")
        exe.map(helper, path_to_wavs)

In [19]:
# subject_folders = os.listdir(BRONZE_DATA_DIR.format(DATA_DIR=DATA_DIR, FOLDER_NAME=BRONZE_FOLDER_NAME))
# len(subject_folders)

In [21]:
# local
ingest_signals(path_to_wavs, DATA_DIR=DATA_DIR)

running


c:\Users\larry.cueva\AppData\Local\anaconda3\envs\signal-gender-predictor\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


shape of audio signals (86000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (100000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 47613 47614 47615]
[    0     1     2 ... 63485 63486 63487]
shape of audio signals (94000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 61949 61950 61951]
shape of audio signals (104000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 63485 63486 63487]
shape of audio signals (72000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 39421 39422 39423]
shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 61949 61950 61951]
shape of audio signals (86000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 43517 43518 43519]
shape of audio signals (82000,)
sampling rate of audio signals after inte

In [ ]:
# # cloud
# ingest_signals(subject_folders, DATA_DIR=None)

running


c:\Users\larry.cueva\AppData\Local\anaconda3\envs\signal-gender-predictor\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


shape of audio signals (122000,)shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (74000,)
sampling rate of audio signals after interpolation: 16000

sampling rate of audio signals after interpolation: 16000
shape of audio signals (100000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (76000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (86000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (104000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (110000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (94000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (136000,)
sampling rate of audio signals after interpolation: 16000
sha