In [1]:
import os
import io
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrowfs_adlgen2 as pa_adl
import numpy as np
import librosa
import datetime as dt

from dotenv import load_dotenv
from pathlib import Path

from azure.identity import DefaultAzureCredential, ClientSecretCredential
from azure.storage.filedatalake import DataLakeServiceClient
from azure.keyvault.secrets import SecretClient
from azure.core.exceptions import ResourceNotFoundError

from concurrent.futures import ThreadPoolExecutor

In [31]:
DATA_DIR = "../../include/data"

In [32]:
# local
BRONZE_FOLDER_NAME = "bronze"
BRONZE_DATA_DIR = os.path.join("{DATA_DIR}", "{FOLDER_NAME}").replace("\\", "/")
BRONZE_DATA_DIR

'{DATA_DIR}/{FOLDER_NAME}'

In [2]:
# Retrieve credentials from environment variables
# this is strictly used only in development
# load env variables
env_dir = Path('../../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

True

In [3]:
storage_account_name = os.environ.get("STORAGE_ACCOUNT_NAME")
credential = os.environ.get("STORAGE_ACCOUNT_KEY")
conn_str = os.environ.get("STORAGE_ACCOUNT_CONN_STR")

In [33]:
# cloud
URL = "abfss://{FOLDER_NAME}@sgppipelinesa.dfs.core.windows.net"
BRONZE_FOLDER_NAME = "sgppipelinesa-bronze"
BRONZE_DATA_DIR = os.path.join(URL.format(FOLDER_NAME=BRONZE_FOLDER_NAME)).replace("\\", "/")
BRONZE_DATA_DIR

'abfss://sgppipelinesa-bronze@sgppipelinesa.dfs.core.windows.net'

In [48]:
# cloud
# create client with generated sas token
datalake_service_client = DataLakeServiceClient(
    account_url=f"https://{storage_account_name}.dfs.core.windows.net", 
    credential=credential
)


# retrieves file system client/container client 
# to retrieve datalake client
bronze_container_client = datalake_service_client.get_file_system_client(f"{storage_account_name}-bronze")

# https://sgppipelinesa.dfs.core.windows.net/sgppipelinesa-bronze
bronze_container_client_url = bronze_container_client.url

# https://sgppipelinesa.blob.core.windows.net/sgppipelinesa-bronze/1028-20100710-hne/wav/ar-01.wav
subject_folders = [
    path.name 
    for path in bronze_container_client.get_paths() if not "/" in path.name
]
subject_folders

['1028-20100710-hne',
 '1337ad-20170321-ajg',
 '1337ad-20170321-tkg',
 '1snoke-20120412-hge',
 '23yipikaye-20100807-ujm',
 'Aaron-20080318-kdl',
 'Anniepoo-20140308-bft',
 'Anniepoo-20140308-cqj',
 'Anniepoo-20140308-fcp',
 'Anniepoo-20140308-hns',
 'Anniepoo-20140308-nky',
 'Coren-20141121-pxp']

In [45]:
[path.name for path in bronze_container_client.get_paths(path='1028-20100710-hne/wav')]

['1028-20100710-hne/wav/ar-01.wav',
 '1028-20100710-hne/wav/ar-02.wav',
 '1028-20100710-hne/wav/ar-03.wav',
 '1028-20100710-hne/wav/ar-04.wav',
 '1028-20100710-hne/wav/ar-05.wav',
 '1028-20100710-hne/wav/ar-06.wav',
 '1028-20100710-hne/wav/ar-07.wav',
 '1028-20100710-hne/wav/rp-29.wav',
 '1028-20100710-hne/wav/rp-30.wav',
 '1028-20100710-hne/wav/rp-31.wav']

In [60]:
def ingest_signals(subject_folders: list[str], DATA_DIR: str=None):

    def helper(subject_folder):
            
        # for folder in folders:
        try:
            # # local
            # # lists out the files containing the .wav files in
            # # a subjects folder. Note also that using double backslash
            # # is not accepted by azure and will raise `path does not exist
            # # or `files can not exist on the root account level` that's
            # # why we replace it always with forward slashes
            # wavs_dir = os.path.join(DATA_DIR, "bronze", subject_folder, "wav").replace("\\", "/")
            # path_to_wavs = os.listdir(wavs_dir)

            wavs_dir = os.path.join(subject_folder, "wav").replace("\\", "/")
            path_to_wavs = [
                path.name 
                for path in bronze_container_client.get_paths(path=wavs_dir)
            ]
        
        except (ResourceNotFoundError, FileNotFoundError):
            # # local
            # # this is if a .wav file is not used as a 
            # # directory so try flac 
            # wavs_dir = os.path.join(DATA_DIR, "bronze", subject_folder, "flac").replace("\\", "/")
            # path_to_wavs = os.listdir(wavs_dir)

            # cloud
            # this is if a .wav file is not used as a directory so 
            # try flac 
            wavs_dir = os.path.join(subject_folder, "flac").replace("\\", "/")
            path_to_wavs = [
                path.name 
                for path in bronze_container_client.get_paths(path=wavs_dir)
            ]

        finally:
            # create storage for list of signals to all be 
            # concatenated later
            signal_list = []
            
            # create storage list for the ordinal positioning
            # of signals to all be concatenated later
            file_row_num_list = []
            file_name_list = []
            loaded_at_list = []
            
            for index, path_to_wav in enumerate(path_to_wavs):
                # cloud
                wav_file_client = bronze_container_client.get_file_client(path_to_wav)

                # Download the file content
                download_result = wav_file_client.download_file()
                downloaded_bytes = download_result.readall()
                audio_buff = io.BytesIO(downloaded_bytes)

                # # local
                # audio_buff = os.path.join(wavs_dir, wav)

                # let librosa read the audio buffer containing t+he content
                # of the binary audio file
                y, sr = librosa.load(audio_buff, sr=16000)

                # audio recordings can have different length
                print(f"shape of audio signals {y.shape}")
                print(f"sampling rate of audio signals after interpolation: {sr}")

                # top_db is set to 20 representing any signal belows
                # 20 decibels will be considered silence
                y_trimmed, _ = librosa.effects.trim(y, top_db=20)
                
                # get how many elements/signals there are in the trimmed
                # version
                # >>> y_trimmed, _ = librosa.effects.trim(np.array([[1, 2, 3, 4, 0, 0, 0]]), top_db=20)
                # >>> y_trimmed.shape
                # (1, 7)
                # ordinal positioning will be 0, 1, 2, 3, 4, 5, 6, 7
                ordinal_positioning = np.arange(y_trimmed.shape[0])
                print(ordinal_positioning)

                # append y to ys 
                signal_list.append(y_trimmed)
                file_row_num_list.append(ordinal_positioning)
                file_name_list.append(np.array(
                    [os.path.join(bronze_container_client.url, path_to_wav)] * y_trimmed.shape[0],
                ))
                loaded_at_list.append(np.array(
                    [dt.datetime.now()] * y_trimmed.shape[0], 
                    dtype='datetime64[us]'
                ))

                # concatenate all audio signals into one final signal as 
                # this is all anyway recorded in the voice of the same gender
                signals = np.concatenate(signal_list, axis=0)
                file_row_num = np.concatenate(file_row_num_list, axis=0)
                file_name = np.concatenate(file_name_list, axis=0)
                loaded_at = np.concatenate(loaded_at_list, axis=0)

                # create pyarrow table so we can write this table as
                # parquet file format later
                table = pa.table({
                    "signals": pa.array(signals), 
                    "subject_id": pa.array([subject_folder] * signals.shape[0], type=pa.string()),
                    "file_row_number": pa.array(file_row_num),
                    "file_name": pa.array(file_name), 
                    "loaded_at": pa.array(loaded_at)
                })

                # # cloud
                # # write the pyarrow table to azure data lake using
                # # pyarrow azure file system using the credential we
                # # retrieved which uses the function apps system assigned 
                # # managed identity
                # SILVER_FOLDER_NAME = f"{storage_account_name}-silver"
                # SUB_FOLDER_NAME = "stage-01"
                # FILE_NAME = f"{subject_folder}_signals.parquet"

                # SILVER_DATA_PATH = os.path.join(SILVER_FOLDER_NAME, SUB_FOLDER_NAME, FILE_NAME).replace("\\", "/")
                # handler = pa_adl.AccountHandler.from_account_name(storage_account_name, credential=credential)
                # fs = pa.fs.PyFileSystem(handler)
                # pq.write_table(table, SILVER_DATA_PATH, filesystem=fs)

                # local
                SILVER_FOLDER_NAME = f"silver"
                SUB_FOLDER_NAME = f"stage-01"
                FILE_NAME = f"signals_{index}.parquet"
                
                # make directory where the numpyfied signals
                # will live
                SILVER_DATA_DIR = os.path.join(DATA_DIR, SILVER_FOLDER_NAME, SUB_FOLDER_NAME, subject_folder)
                os.makedirs(SILVER_DATA_DIR, exist_ok=True)
                
                # 
                SILVER_DATA_PATH = os.path.join(DATA_DIR, SILVER_FOLDER_NAME, SUB_FOLDER_NAME, subject_folder, FILE_NAME).replace("\\", "/")
                pq.write_table(table, SILVER_DATA_PATH)
                
        return
            
    # concurrently load .wav files and trim  each .wav files
    # audio signal and combine into one signal for each subject 
    with ThreadPoolExecutor(max_workers=5) as exe:
        print("running")
        exe.map(helper, subject_folders)

In [56]:
# subject_folders = os.listdir(BRONZE_DATA_DIR.format(DATA_DIR=DATA_DIR, FOLDER_NAME=BRONZE_FOLDER_NAME))
# len(subject_folders)

In [61]:
# local
ingest_signals(subject_folders[:], DATA_DIR=DATA_DIR)

running
shape of audio signals (100000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 63485 63486 63487]
shape of audio signals (86000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 47613 47614 47615]
shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 60413 60414 60415]
shape of audio signals (104000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 63485 63486 63487]
shape of audio signals (94000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 61949 61950 61951]
shape of audio signals (74000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (76000,)
sampling rate of audio signals after interpolation: 16000
[    0     1     2 ... 44029 44030 44031]
[    0     1     2 ... 49661 49662 49663]
shape of audio signals (122000,)
sampling rate of audio signals a

In [ ]:
# # cloud
# ingest_signals(subject_folders, DATA_DIR=None)

running


c:\Users\larry.cueva\AppData\Local\anaconda3\envs\signal-gender-predictor\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


shape of audio signals (122000,)shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (74000,)
sampling rate of audio signals after interpolation: 16000

sampling rate of audio signals after interpolation: 16000
shape of audio signals (100000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (76000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (86000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (104000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (110000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (94000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (106000,)
sampling rate of audio signals after interpolation: 16000
shape of audio signals (136000,)
sampling rate of audio signals after interpolation: 16000
sha